services:
  db:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: candidate1
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_DATABASE: candidate1
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
    ports:
      - '8080:80'
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:
    driver: bridge
